apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasma-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: plasma-app
  template:
    metadata:
      labels:
        app: plasma-app

    spec:
      containers:
        - name: plasma-app-container
          image: uk.icr.io/kub_ns/deployplasmaimage3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
